print('Tell us a few words about yourself, please')
name=input('What is your name?')
age=int(input('How old are you?'))
sex=input('What is your gender?')
weight=int(input('what is your weight?'))
height=int(input('What is your height?'))
result="Your name is %s, your age is %i, your sex is %s, your weight is %i, your height is %i" %(name, age, sex, weight, height)
print(result)
file=open('questionnaire.txt', 'w')
file.write(result)
file.close()
