name = input("Enter your name:")
surname = input("Enter your surname:")
age = int(input("Enter your age:"))
car = input("What is your car?:")
hometown = input("Where are you from?:")

output_text = "Your name is %s %s, You are %i years old, Your car is %s, You are from %s!" %(name,surname,age,car,hometown)
output_file = open("output.txt", "w")
output_file.write(output_text)
output_file.close()