print ("Hello! We are glad to see you on our site! To create account please answer the following questions:")
name = input("Your name?")
surname = input("Your surname?")
age = input("Your age?")
job = input("Your job?")
phone = input("Your phone number?")
data = ("Name, surname: %s %s; age: %s; job: %s; phone number: %s."%(name, surname, age, job, phone))
print(data)
file = open ("data.txt", "w")
file.write(data)
file.close()