name = input("What is your name? ")
age = int(input("How old are you? "))
city = input("Where do you live? ")
university = input("Where do you study? ")
say_for_self = ("My name is %s, my age is %i, "
                "i live in %s and i study in %s" % (name, age, city, university))
print(say_for_self)
f = open('homework.txt', 'r')
f = open('homework.txt', 'w')
f.write(say_for_self)
f.close()
