# version 1
name = input("What is your name? ")
surname = input("What is your surname? ")
age = input("How old are you? ")
city = input("Where do you live? ")
file_out_one = open('About_myself.txt', 'w')
file_out_one.write(name+'\n')
file_out_one.write(surname+'\n')
file_out_one.write(age+'\n')
file_out_one.write(city)
file_out_one.close()
# version 2
file_out_two = open("About_my_family.txt", 'w')
print(input('What is your mother name? ') + '\n' + input("What is your father name? "), file=file_out_two)
file_out_two.close()
print('Your data save to file')
